fragment EventsParts on Events {
  __typename
  title
  date
  presenter
  presenterTitle
  startTime
  endTime
  location
  zoomLink
  description
  image
  youtubeId
  status
  body
}

fragment PagesParts on Pages {
  __typename
  title
  description
  pageLayout
  parent
  showInNav
  navOrder
  heroGradient
  body
  contactInfo {
    __typename
    email
    location
    address
  }
}

fragment SettingsParts on Settings {
  __typename
  siteTitle
  siteDescription
  contactEmail
  socialMedia {
    __typename
    facebook
    youtube
    meetup
  }
  meetingInfo {
    __typename
    time
    locationName
    locationAddress
    defaultZoomLink
  }
}

fragment JoinParts on Join {
  __typename
  heroHeading
  heroTagline
  benefitsHeading
  benefits {
    __typename
    title
    description
  }
  personalInfoHeading
  personalFields {
    __typename
    label
    fieldName
    fieldType
    required
    placeholder
  }
  philosophyText
  membershipNote
  membershipTiers {
    __typename
    tierName
    tierSubtitle
    priceRange
  }
  communicationPrefsHeading
  communicationFields {
    __typename
    label
    description
    fieldName
    defaultChecked
  }
  questionsHeading
  questionsBody
  membershipEmail
  questionsFootnote
}

fragment HomepageParts on Homepage {
  __typename
  heroHeading
  heroTagline
  humanismHeading
  humanismBody1
  humanismBody2
  features {
    __typename
    title
    description
  }
  ctaHeading
  ctaBody
}
